### PR TITLE
working use a fysom state machine

### PR DESCRIPTION
**Pull request by alefur**
I think that's working as it supposed to, what do you think ?

### CODE REVIEW

**Comment by CraigLoomis** [comment]
Yup: just the right place for a state machine!
Just one question: is that 5 seconds or 5 minutes? I don't see any conversions, and 5 seconds feels very short: don't we need to wait for the turbo to spin up?
[ And if I were being careful I'd add a callback to the turbo speed keyword, etc. and clear the standby state when it reaches 90k. ]

**Comment by alefur** [comment]
Yes, I've put five seconds to test and have forgotten to change the value after that.
Good point ! Same for cooler power I suppose ?

**Comment by alefur** [comment]
I had to cleanup and force-push. Sorry, my mistake...
Anyhow, the mechanism in now in place, including the callback on turboSpeed for the pumpdown mode. 
In the end, for the cooldown mode, it's not as trivial, since it would have to check at multiple subsystem(cooler, gatevalve ...).

**Comment by alefur** [comment]
merge ??

**Comment by CraigLoomis** [comment]
Sorry -- missed the follow ups. Looks good.

**Pull request merged**
